# Generated by Django 3.1.7 on 2021-03-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookbazaar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
