# Generated by Django 3.1.7 on 2021-03-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbazaar', '0003_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='soldby',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
