# Generated by Django 3.1.7 on 2021-03-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbazaar', '0004_product_soldby'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='boughtby',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
