# Generated by Django 3.1.7 on 2021-03-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbazaar', '0006_order_orderitem_sellitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='soldby',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
