# Generated by Django 3.1.7 on 2021-03-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookbazaar', '0007_auto_20210324_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='orderitem',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
    ]
